### ISSUE TITLE
Disable Bracket Matcher During Paste To Prevent Performance Issue When Pasting 1600 Lines Of Text

### ISSUE THREAD

**Issue by joefitzgerald** [atom/bracket-matcher#103]
Can we please disable bracket matcher during a paste event?

Best depicted through a profile of the activity. 
1. Open the inspector
2. Start a CPU profile
3. Paste [this file](http://beta.json-generator.com/FsMfeBZ) into an empty JSON file
4. Stop the CPU profile
5. Observe a **huge** performance issue

![screen shot 2015-01-30 at 4 41 24 pm](https://cloud.githubusercontent.com/assets/744740/5985431/4d61a550-a89f-11e4-8033-1bd7cc89bd01.png)

**Comment by Pugio** [comment]
Fixes to this would be hack-ish, at the moment, as Atom doesn't seem to expose any useful events around paste. Either an event in TextEditor.pasteText or, better, a 'finished-dispatch' event hook on the global command registry.
