### ISSUE TITLE
Compatibility problem with Oniguruma

### ISSUE THREAD

**Issue by Veejay** [atom/bracket-matcher#111]
Hi,

I am not sure I fully understand the technical intricacies of this issue so I'll just paste what information Atom is giving me: 

```
Bracket Matcher 0.71.0Check for UpdateReport IssueDisable Package
Listed below are the incompatible native modules that this package depends on.

oniguruma@4.0.0
Error message: Module version mismatch. Expected 41, got 17.
```

And 

```
If no update is available you may want to notify the package author that their package isn't supported in Atom 0.184.0 because of the Chrome 40.0.2214.91 and Node 1.0.0-pre upgrade.
```

It's a shame because I heavily rely on your most excellent package.

**Comment by lee-dohm** [comment]
Which version of Atom are you using? I don't see that error.

**Comment by kevinsawicki** [comment]
@Veejay do you have bracket-matcher installed to `~/.atom/packages/bracket-matcher`?

**Comment by Veejay** [comment]
@lee-dohm Hi, I'm currently using Atom 0.184.0

@kevinsawicki I do have a directory in `~/.atom/packages/bracket-matcher`, but this was installed through Atom's Preferences tab (searching for the package and clicking install).

Here's a screenshot of the issue (as reported in the bottom status bar when starting Atom).
![screen shot 2015-02-27 at 15 48 02](https://cloud.githubusercontent.com/assets/59471/6414492/244eb928-be98-11e4-81b2-9b768bfb305b.png)

Note that the package has worked before to my entire satisfaction, it's just been a bumpier ride for the past releases of Atom (always due to an Oniguruma version mismatch).

**Comment by lee-dohm** [comment]
@kevinsawicki's point is that bracket-matcher is a default-installed package, so you don't need it installed a second time in `~/.atom/packages` ... and in the past, this has caused problems. If you uninstall it from `~/.atom/packages` and restart Atom things should work fine. If not, let us know!

**Comment by kevinsawicki** [comment]
Closing this out, deleting `~/.atom/packages/bracket-matcher` and then restarting Atom should fix this as @lee-dohm mentioned.

**Comment by Veejay** [comment]
Works perfectly, I am now a satisfied customer, thanks to the both of you.
