### ISSUE TITLE
Improve brace matching

### ISSUE THREAD

**Issue by 50Wliu** [atom/bracket-matcher#116]
_From @mindplay-dk on March 15, 2015 14:10_

Brace matching in ATOM is like this:

![image](https://cloud.githubusercontent.com/assets/103348/6656256/f2c59dde-cb23-11e4-9d61-16c3cc9c43e3.png)

In e.g. Php Storm, brace matching prioritizes parens based on their direction - like this:

![image](https://cloud.githubusercontent.com/assets/103348/6656258/15b2e4dc-cb24-11e4-9617-a81e7ba765dc.png)

Why this is better: because, regardless of whether the cursor is over an opening or closing brace, it's matched in such a way that you're typing _outside_ the matching parens - consistently.

The way it works in ATOM currently, if I start typing in the first example, I'm typing on the outside of the matched parens - but if I start typing in the second example, I'm typing inside the matched parens. 

Having to cursor right before you start typing after a closing brace, and then having the "wrong" parens highlight when you do, is really confusing.

_Copied from original issue: atom/atom#5973_

**Comment by JulianLeviston** [comment]
I can't really use Atom until this is addressed.

**Comment by quatrezoneilles** [comment]
How can thousands and thousands of atom users put up with this?  This is a major issue!

**Comment by GetContented** [comment]
@quatrezoneilles maybe they don't notice ;-)

**Comment by dmohs** [comment]
This is a constant annoyance for me and impedes my workflow to the point that I'm willing to try to fix it myself. I suspect some modification around here would do the trick:

https://github.com/atom/bracket-matcher/blob/master/lib/bracket-matcher-view.coffee#L165

I'd appreciate any pointers.

**Comment by dmohs** [comment]
The above PR causes `bracket-matcher` to exhibit the correct behavior in my own testing.
