### ISSUE TITLE
Select inside brackets for HTML files doesn't consider HTML attributes

### ISSUE THREAD

**Issue by izuzak** [atom/bracket-matcher#117]
Originally reported over at https://github.com/atom/atom/issues/6008 (thanks @philsinatra!).

Example:

``` html
<div class="wrapper">
  <div class="main">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti ipsam ullam magni minus, aperiam animi, quasi corporis. Impedit expedita, excepturi, iure corporis quo maxime, aperiam perferendis voluptas praesentium sint quam.</p>
  </div>
</div>
```

Position the cursor after `class="wrapper">` and execute the "Select inside brackets" command. Result:

![screen shot 2015-03-18 at 18 43 34](https://cloud.githubusercontent.com/assets/38924/6715602/dc81038c-cd9f-11e4-812f-4d65fdd14279.png)

Instead, I expected to see this:

![screen shot 2015-03-18 at 18 52 37](https://cloud.githubusercontent.com/assets/38924/6715626/fa558392-cd9f-11e4-8f67-649da1f3deaf.png)

I'm guessing that the command doesn't expect it will see any attributes, so it just selects starting from where it thinks the `>` of the opening tag will be?

**Comment by junaidbhura** [comment]
+1 this would be great to have - such an important part of my workflow!

**Comment by Jheysoon** [comment]
any updates ? . . .
:+1: in this feature

**Comment by prezmo** [comment]
Very annoying bug. Any known workarounds?

**Comment by tupini07** [comment]
+1

**Comment by renatogalvones** [comment]
+1

**Comment by TomByte** [comment]
For anyone looking for a workaround, the [Emmet plugin](https://github.com/emmetio/emmet-atom) has the command "Balance (outward)".

Have a look at the [default keybind list](https://github.com/emmetio/emmet-atom#default-keybindings) for your native system hotkey.

**Comment by revelt** [comment]
+1

**Comment by Lazerproof** [comment]
+1

**Comment by oyazik** [comment]
is there any update?

**Comment by raptor235** [comment]
+1

**Comment by karson** [comment]
this issue persists

**Comment by Ben3eeE** [comment]
@karson This is currently scheduled for release in Atom 1.22

**Comment by revelt** [comment]
This one is awesome, will save lots of peep's time. Imagine if you deal with HTML and are able to instantly replace content between the tags or delete it... some many possibilities... I use the JS equivalent daily.
