### ISSUE TITLE
Enable "Select Inside Brackets" fonctionnality to other plateforms

### ISSUE THREAD

**Issue by brunetton** [atom/bracket-matcher#124]
Hi all, 

Just wondering: why Select Inside Brackets functionality seems to be only accessible to Mac versions, not Linux versions of Atom ? (`.plateform-darwin` un shortcuts json file).

In Linux, the display of matching bracket is working fine (even if I deactivate bracket-matcher), so I say to myself : If it's possible to display corresponding element, it should be simple to select chars or lines beetweens that corresponding elements no ?

I looked around and found that *emmet* does that. I'll have a check, but I wonder why it's not part of basic Atom packages.

Thanks !

**Comment by lee-dohm** [comment]
It looks like it was moved to a Mac-specific keybinding and nobody ever added it to the Linux or Windows keybindings. Can you map a keybinding (in your `keymap.cson`) like this and see if it works for you?

```coffee
'atom-text-editor'
 'ctrl-shift-alt-z': 'bracket-matcher:select-inside-brackets'
```

If it does, it is a simple matter to add the missing keymap to the other platforms.

Alternatively, you can just search for "selectinside" in the Command Palette. I bet it shows up there and works just fine.

If you feel comfortable submitting a PR, you can add the missing keymap or let me know what the results are and I can submit it later.

**Comment by brunetton** [comment]
Hi, yes of course, it was the first thing I tried : add a key mapping, and the result was quite strange. I was on an mako html file, well indented,  (all openings tags have matching closing tags), but it selected a text between braces, at a totally different place in the document. 
This is why I asked, maybe there is a reason why it works only on Mac environment (I don't see why, no system calls should be happen here). 

Maybe is this only a mako problem, I'll try with a standard simple html file and come back to you! (I'm actually on my cellphone, not possible to test now)

**Comment by brunetton** [comment]
Thanks for the commit, it's a good start !
But `ctrl-alt-m` is used for a long time for [minimap] (https://atom.io/packages/minimap).

Why don't use `ctrl-shift-m` here ? As it has been discused in atom/bracket-matcher#17:

as @lloeki said:
> There are not much brackets in markdown, and the keybinding is active only in Markdown documents.
>
> Also other keybindings would really make no sense: when "action" does a movement, people reasonably usually (i.e. about 297% of the time) expect "Shift+action" to move and select.

and @kevinsawicki :
> I added this feature but bound it to ctrl-cmd-m to start with to no conflict, it will be included in the 0.85.0 release. We can discuss changing keybindings in a different PR/issue, I definitely see your point though about ctrl-shift-m being the expected keybinding for this action.

It's also what's being requieted by @dmnd that opened atom/markdown-preview#114

> I'm suggesting that markdown-preview use another keybind so that bracket-matcher can use ctrl-shift-m by default.
>
> ctrl-m is used by bracket-matcher to navigate the cursor to a bracket. It makes sense for the shift key to convert this cursor movement action to a selection action, however ctrl-shift-m is already used by markdown-preview. Note that ctrl-m and ctrl-shift-m are the keybinds used by Sublime too.
>
> Another option would be to reduce the scope of markdown-preview's bind to only Markdown docs, but that would still prevent bracket matching working in Markdown docs and that might be annoying if the doc has code snippets in it. Also it's just generally inconsistent.
> 
>I totaly agree with the idea that `shift` *must* be part of the shortkey, and must also be the only key to add to shortkey.

I've nothing to add to this explanation, it's exactely that should be done in my opinion.
I just wait for @kevinsawicki green light to propose pull requests to:
  - *markdown-preview* for shortkey only be activated in markdown documents, or just change key binding to *something else* (I've no idea for now)
  - *bracket-matcher* for change shortkey to `ctrl-shift-m`

**Comment by cbenz** [comment]
+1 ctrl-shift-m

**Comment by brunetton** [comment]
While waiting for the pull request to be included on next Atom release, we can customize our `keymap.cson` adding this :

<pre>
'atom-text-editor':
  'ctrl-shift-m': 'bracket-matcher:select-inside-brackets'
'atom-text-editor[data-grammar="source gfm"]':
  'ctrl-shift-m': 'markdown-preview:toggle'
</pre>

**Comment by lloeki** [comment]
>  just change key binding to something else (I've no idea for now)

This might be the moment to propose that *-preview (where, * is markdown, svg, png or whatever) could have a common "open preview shortcut").
