### ISSUE TITLE
Adjust color/style of bracket-matcher?

### ISSUE THREAD

**Issue by smlombardi** [atom/bracket-matcher#125]
Currently, it puts a tiny hard-to-see light green underline.

Where can I edit this in my styles.less to something more obvious to me?

**Comment by Wexx** [comment]
Bracket-matcher/styles/bracket-matcher.atom-text-editor.less, uses border-bottom property by default http://www.w3schools.com/cssref/pr_border-bottom.asp

**Comment by smlombardi** [comment]
I was trying to get it to be background-color in a addition to the border-bottom, to be more visible.  However, if I apply such parameters to my styles.less only the OPPOSITE tag gets the bgcolor -- the one where the cursor is does not.

**Comment by Wexx** [comment]
That's strange, can you post what you have in your style.less? Both of my brackets have the applied  when I open a new file.

Mine is absolutely hideous right now, but I have 

`.bracket-matcher .region {
  border-bottom: thick dotted yellow;
  background-color: orange;
  position: absolute;
}`

**Comment by smlombardi** [comment]
````
atom-text-editor::shadow  .bracket-matcher .region {
    border-bottom: 1px solid #de9536;
    background-color: #ffd900;
    opacity: 0.7;
}
````

![screen shot 2015-04-24 at 3 57 46 pm](https://cloud.githubusercontent.com/assets/835148/7327382/ab721ffc-ea9a-11e4-8e94-1fe5fb07508c.png)

**Comment by smlombardi** [comment]
I see both only when Atom is in the background.

**Comment by wmakeev** [comment]
@smlombardi, current line highlighting override bracket-matcher background.

You can set line background opacity:

```css
atom-text-editor::shadow .lines .line.cursor-line {
   background-color: rgba(228, 246, 212, 0.7);
}
```

**Comment by vdun** [comment]
and how to change the text color ?

**Comment by gegillam** [comment]
I would also like to know if its possible to change the underlying text color on matching brackets.

**Comment by Wexx** [comment]
You can use less/css properties to modify the styling options on how the text appears (using the class you have to add to the files discussed above). You have to close and re-open atom for the changes to take effect.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by ofod1n** [comment]
this is easy c:program files(x86) brackets in search
dark theme and in folder again search main.less and edit
ctrl +f 2e5c00 this is default color and change so save ;)

**Comment by leandrosiow** [comment]
Is it possible to highlight the whole chunk of code like outline it instead of just the actual "bracket" character? I think it is called high-visibility. Thanks.

**Comment by CubeOfCheese** [comment]
I don't believe there is a way to do this because there are no parent selectors in css.

**Comment by calebmeyer** [comment]
If I'm reading the API correctly, @leandrosiow, this should be possible to do with DisplayMarkers and Decorations: https://atom.io/docs/api/v1.38.2/Decoration

Basically you could check for the ranges created whenever the bracket-matcher markers are created, create a new range between them, a new marker on that range, and a decoration on that marker.

I'm sure this repo would accept a well formed PR, based on their [CONTRIBUTING.md file](https://github.com/atom/bracket-matcher/blob/master/CONTRIBUTING.md)
