### ISSUE TITLE
bracket-matcher:close-tag problems with TH tag

### ISSUE THREAD

**Issue by mnquintana** [atom/bracket-matcher#133]
_From @Instagit on May 11, 2015 15:33_

Atom Version: 0.196

Keybinding:

``` cson
'.platform-linux atom-text-editor':
  'alt-.': 'bracket-matcher:close-tag'
```

Closing this `<th>` tag doesn't work:

``` html
<table>
  <thead>
    <tr>
      <th>
    </tr>
  </thead>
</table>
```

It works with `<td>`, if you omit only the closing `</thead>` or if you remove the `<thead>` tags completely.

According to the HTML5 specification it doesn't need to be closed, but the behaviour is inconsistent.

_Copied from original issue: atom/atom#6740_

**Comment by 50Wliu** [comment]
This is happening because for whatever reason bracket-matcher is matching prefixes.
```html
<table>
  <thblablabla>
    <tr>
      <th>
    </tr>
  </thblablabla>
</table>
```
would fail as well, because it sees the starting `th` and goes "yup, that's the th tag".  Also somewhat related to #79.
