### ISSUE TITLE
skipOverExistingClosingBracket doesn't work after escape sequence

### ISSUE THREAD

**Issue by itsadok** [atom/bracket-matcher#164]
Typing `"hello\n"` in a new window results in `"hello\n""`, with the caret placed before the last quote.

(Conversely, typing `"hello"` results in the more sensible result of `"hello"`.)

Looks like the problem is [here](https://github.com/atom/bracket-matcher/blob/a36bd33a2f0c3a8e19aba441e881360c57bbd44c/lib/bracket-matcher.coffee#L58), but I can't figure out what the original intention for `hasEscapeSequenceBeforeCursor` was.

**Comment by jeancroy** [comment]
Duplicate of https://github.com/atom/bracket-matcher/issues/80
Possible fix here https://github.com/atom/bracket-matcher/pull/160

**Comment by itsadok** [comment]
Oops, sorry.
