### ISSUE TITLE
Access BracketMatcher object from another package?

### ISSUE THREAD

**Issue by seanlaff** [atom/bracket-matcher#165]
Hi there,

I was hoping to extend some of the functionality of this package into my own. In my package I am trying to apply styling to the block of code my cursor is currently in. I could easily achieve this functionality using some helper methods that are in the BracketMatcher class but I don't want to create another BracketMatcher object if this package already creates one. However, I don't think this package exports the BracketMatcher it creates? I'm new to atom development, so any guidance would be appreciated.

Thanks!

**Comment by kevinsawicki** [comment]
> However, I don't think this package exports the BracketMatcher it creates?

It currently does not export any official API at this time. It could be added as a service with an API, what are you trying to use it for?

**Comment by seanlaff** [comment]
Sublime's `BracketHighlighting` plugin has a feature called "High Visibility Mode" which highlights the scope you are currently in. It's really useful when you are working in messy nested javascript and html and want to visibility see which block you're in. 

I wanted to create a package that is a thin wrapper around this bracket-matcher package that does customizable highlighting from start bracket to ending bracket. 

![screen shot 2015-07-28 at 12 04 50 pm](https://cloud.githubusercontent.com/assets/3194832/8936572/0d11b404-3521-11e5-96b7-ad95556f645c.png)

**Comment by kevinsawicki** [comment]
You could look into externally using the markers this package creates in https://github.com/atom/bracket-matcher/blob/2bc7df4cd47115caa70e41acdf815aa928f7b78f/lib/bracket-matcher-view.coffee#L179 as a starting point.

Otherwise your options are either to add it to this package, copy code from here, or directly require code from here (which would be fragile).

**Comment by seanlaff** [comment]
Thanks for the clarification. I'm going to toy around with it and if I come up with anything I'll issue a PR to see what you think.

**Comment by kevinsawicki** [comment]
Great, thanks, closing this out for now.
