### ISSUE TITLE
Select to matched bracket

### ISSUE THREAD

**Issue by lloeki** [atom/bracket-matcher#17]
Ctrl-M places the cursor to a bracket according to some rule. Ctrl-Shift-M should smartly† select from the current cursor position to the new one.

† This is very useful for indenting blocks, changing function arguments, modifying array/dict/hash indices or content... so best judgement must be used to set the selection properly. E.g calling it twice in a row from anywhere inside a bracketed array or parens should select whatever the _inside_ of the brackets is. Calling it a third time could grow the selection to _include_ the brackets.

Inspiration: vim's `ci[`/`di[`/`ca[`/`da[`

**Comment by brunetton** [comment]
Referenced in atom/bracket-matcher#124

**Comment by brunetton** [comment]
Referenced in https://github.com/atom/markdown-preview/pull/249

**Comment by brunetton** [comment]
While waiting for the pull request to be included on next Atom release, we can customize our `keymap.cson` adding this :

<pre>
'atom-text-editor':
  'ctrl-shift-m': 'bracket-matcher:select-inside-brackets'
'atom-text-editor[data-grammar="source gfm"]':
  'ctrl-shift-m': 'markdown-preview:toggle'
</pre>
