### ISSUE TITLE
Rainbow

### ISSUE THREAD

**Issue by johngeorgewright** [atom/bracket-matcher#170]
Hey,

I was just about to attempt writing a package for rainbow parenthesis, to achieve something like the following:

![Rainbow Parens](https://doingmyprogramming.files.wordpress.com/2014/12/rainbow-delimeters.png)

During a bit of investigation I realised you've already done all the hard work of matching parenthesis in atom. It got me thinking, that maybe `bracket-matcher` could have configuration to turn rainbow parens on and off and was wondering how you'd feel about accepting a pull request?

If you think it's outside the scope of `bracket-matcher` then is there any way I can re-use some of what you've done in another package?

Thanks,
John

**Comment by maxlevesque** [comment]
That would be amazing.

**Comment by WalterGR** [comment]
I haven't tried it, but someone released a package recently that ostensibly does this: "My first package released (Coloured brackets)" - https://discuss.atom.io/t/my-first-package-released-coloured-brackets/21261.

**Comment by mixxster** [comment]
I would really really like to see this.

**Comment by jasrusable** [comment]
+1

**Comment by WalterGR** [comment]
I haven't tried it, but someone recently released a package that does something similar: "My first package released (Coloured brackets)" - https://discuss.atom.io/t/my-first-package-released-coloured-brackets/21261.

**Comment by rbdone** [comment]
+1

**Comment by johngeorgewright** [comment]
I've had a look this morning and realised that it really needs to be a separate plugin, this bracket matching is based on the cursor position.
I also checked out Swakets, but it's very slow and buggy, so I've started something of my own. I'll keep you in the loop.
