### ISSUE TITLE
Typing '\n' yields '\n''

### ISSUE THREAD

**Issue by zyklus** [atom/bracket-matcher#172]
![quotes](https://cloud.githubusercontent.com/assets/320562/9405125/94df45b8-4827-11e5-9b85-35d34b15f165.gif)

**Comment by jeancroy** [comment]
I beleive https://github.com/atom/bracket-matcher/pull/160 cover this.

**Comment by 50Wliu** [comment]
Thanks @jeancroy.  This is also a duplicate of #80.
