### ISSUE TITLE
Feature request: customize opening/closing brackets/etc. per-language

### ISSUE THREAD

**Issue by isiahmeadows** [atom/bracket-matcher#182]
## Problem

The current set is a very sensible default for many C-based languages, but several languages, such as Haskell, OCaml, and various Lisps, use some of those characters for other reasons. Examples:

- `'` (single quote)
  - It's a valid identifier character in Haskell, as long as it's not the first. OCaml accepts it anywhere, and it's frequently used in function arguments. `foo'`, `foo''`, etc. is the Haskell counterpart to `foo1`, `foo2`, etc. in most other languages.
  - It denotes symbols in multiple Lisps, including Clojure, and they represent to-be-evaluated identifiers. It's mostly used with macros.
- `` ` `` (backtick)
  - This is the syntax quote in most Lisps, including Clojure.
  - This denotes polymorphic variants in OCaml. It's used occasionally for duck-typing and code reuse, but infrequently because it reduces type safety.
  - This is the escape character in Windows PowerShell.

Most of these are common enough cases that they will appear in most non-trivial projects written in that language.

There's also the more obscure languages that allow for unbalanced braces as well, e.g. APL, J, and Forth.

## Solution

Allow all opening/closing characters to be configured on a per-language basis via the [Atom config](https://atom.io/docs/latest/using-atom-basic-customization) and [Atom services](https://atom.io/docs/latest/behind-atom-interacting-with-packages-via-services). In the case of the latter, anything there effectively becomes the language's default. The current default can stay the default, as it works with most common languages. It can be as simple as this:

**Here:**

```json5
// package.json
{
  "consumedServices": {
    "bracket-matcher": {
      "versions": {
        "1.0.0": "consumeConfig"
      }
    }
  }
}
```

```coffee
# index.coffee
exports.consumeConfig = ({scope, match}) ->
  setAsDefaultConfig(scope, match)
```

**Package:** Clojure as an example

```json5
// package.json
{
  "providedServices": {
    "bracket-matcher": {
      "versions": {
        "1.0.0": "provideConfig"
      }
    }
  }
}
```

```coffee
# index.coffee
exports.provideConfig = ->
  scope: 'source.clojure'
  match: [
    ['(', ')']
    ['{', '}']
    ['[', ']']
    ['"', '"']
  ]
```

Note that the scope name is basically the grammar's `scopeName`.

**Comment by joedaniels29** [comment]
seconding an idea like this. typing ```#'```in lisp is quite difficult.

**Comment by branefreez** [comment]
I third this feature request. I am really getting annoyed with having to manually remove auto-closed backticks in Perl6 with multiline comments of the style #`(COMMENT). I really would hate to have to disable bracket-matcher.

```perl6
#`(
This multiline
comment is
what I want to get.
)
#`(But I get
a backtick at the end.
)`
```

**Comment by otherjoel** [comment]
Another vote in favour. Manually disabling per language is a pain!

**Comment by MadcapJake** [comment]
Another vote for this and another with regards to Perl 6:  there are actually numerous supported enclosing delimiters in the language (most non-letter characters).

Also in template languages there are a lot of unique delimiters chosen out of a need to be different enough to not show up in someone's actual content.

Another language I use (Nit) has a special set of brackets for native code:
```nit
fun sleep( t : Int ) `{ sleep( t ); `}
```

**Comment by boozedog** [comment]
+1 for this enhancement.

**Comment by kebno** [comment]
+1

**Comment by isiahmeadows** [comment]
I think it would come down to parameterizing [these lines](https://github.com/atom/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L7-L24) and enabling them to be mutated via a service. I'm considering taking a stab at this, but I'm time-strapped ATM. :frowning:

**Comment by boozedog** [comment]
As an interim step, can the "non-smart" quotes be a separate toggle similar to smart quotes? That'd certainly solve #171 ...

**Comment by utkarshkukreti** [comment]
I posted a workaround (good enough for me until this gets fixed) here: https://github.com/atom/bracket-matcher/issues/171#issuecomment-239634867 cc @boozedog

**Comment by 50Wliu** [comment]
Closing in favor of #121 - feel free to subscribe there for updates.
