### ISSUE TITLE
issue with escaped bracket string

### ISSUE THREAD

**Issue by iahu** [atom/bracket-matcher#184]
```js
var a = [
  {
    d: ['test\\[\\[\\}\\{\\{',{e:'df'}],
    f: {
      test: 'b4'
    }
  }
];
```

I think "bracket matcher" should not match the escaped bracket.
Atom's `getStartBufferPosition` also has the same problem, as that the `goToMatchingPair` function also can't get the right bracket.

**Comment by izuzak** [comment]
Thanks for the feedback, @iahu -- I think this is already being tracked in https://github.com/atom/bracket-matcher/issues/23, so I'm going to close this in favor of that issue. If I misunderstood your report, can you clearly explain the difference between #23?
