### ISSUE TITLE
How to always highlight nearest matching bracket pair?

### ISSUE THREAD

**Issue by bringingkatigbak** [atom/bracket-matcher#195]
Hi,

If I have an open bracket on line 1, code on lines 2-4 then the closing bracket on like 5. When my cursor is on either lines 1 or 5, the matching bracket is highlighted as expected. However, as I am working on lines 2-4, the highlight on the matching bracket goes away. 

How could I make it stay? I have it this way in sublime and really like it. 

TIA!

Niko

**Comment by lee-dohm** [comment]
There currently isn't support for this feature, but there is an open Issue for it already at https://github.com/atom/bracket-matcher/issues/57. Please subscribe there for updates and thanks for reporting!
