### ISSUE TITLE
JS: incorrect bracket matching

### ISSUE THREAD

**Issue by fruggiero** [atom/bracket-matcher#207]
![image](https://cloud.githubusercontent.com/assets/4760358/12537154/5516d552-c2b8-11e5-8d31-6cd7164f6862.png)

Looks like it doesn't ignore brackets inside comments.

Atom version:  1.4.0

**Comment by 50Wliu** [comment]
Hi @fruggiero, this is a duplicate of #23 and #78 - please subscribe there for updates.
