### ISSUE TITLE
Golang bracket indentation

### ISSUE THREAD

**Issue by davisford** [atom/bracket-matcher#209]
Try this golang code in the editor:

expected:

```go
func someFunc() {
	aSlice := []string{}{
	
	}
}
```

actual:

```go
func someFunc() {
	aSlice := []string{}{
	
}
}
```

The bracket matching seems to get confused by the appearance of a second set of brackets (i.e. the slice initializer), and it always places it on the first character of the next newline when `enter` is committed.

**Comment by 50Wliu** [comment]
As I mentioned in atom/language-go#86, please move this issue over to the language-go repository.  Thanks!
