### ISSUE TITLE
The ability to only show the highlights on [], (), and {}

### ISSUE THREAD

**Issue by josh18** [atom/bracket-matcher#211]
I would like to only show the highlights on `[]`, `()`, and `{}` and not on html tags, is this possible?

**Comment by lee-dohm** [comment]
Not currently, the classes assigned to the highlights are the same. Are you making a feature request?

**Comment by josh18** [comment]
Yes, would you prefer if I made a new issue or just renamed the title on this one? I just wanted to make sure I wasn't requesting an already existing feature.

**Comment by lee-dohm** [comment]
Go ahead and reuse this one :grinning:
