### ISSUE TITLE
Wrong matching for brackets in quotes

### ISSUE THREAD

**Issue by romanfazulianov** [atom/bracket-matcher#213]
Hi! I have such bug: the end bracket of the function is matched to the bracket inside a string in quotes
![2016-02-18 12 17 47](https://cloud.githubusercontent.com/assets/5006121/13138734/deac2cba-d639-11e5-93e4-4ff81274e822.png)

    atom v1.02
    bracket-matcher v0.79.1
    Ubuntu v14.04

**Comment by 50Wliu** [comment]
This is a duplicate of #78 - feel free to subscribe there for updates.

In addition, your Atom version is severely outdated - the latest version is currently 1.5.3.
