### ISSUE TITLE
Customize close [], (), "" or  {}

### ISSUE THREAD

**Issue by francismaile** [atom/bracket-matcher#214]
I find auto-closing brackets, parentheses and quotes mostly annoying but curly braces most useful. It would be great if the settings could be fine-tuned enough to allow these specific choices.

**Comment by ul** [comment]
+1 for fine-grained control over autoclosable set.
My personal frustration is related to single quotes and backticks — it would be fine to disable their autoclosing while writing lisp.

**Comment by zoffixznet** [comment]
+1 I want to autoclose braces and parens only. Autoclosing quotes never seems to work right with the way I use them, so it'd be awesome if there were an option to separate the two.

**Comment by potto007** [comment]
Hi @francismaile, @ul, @zoffixznet - I submitted a pull request yesterday that addresses this. When you get a chance, please try it out and see if it satisfies your needs.

**Comment by 50Wliu** [comment]
Closing in favor of #121 - feel free to subscribe there for updates.
