### ISSUE TITLE
Bracket matches inside JavaScript RegEx literal 

### ISSUE THREAD

**Issue by Siguza** [atom/bracket-matcher#215]
Language: JavaScript

Code:

    function(s)
    {
        return /\}/.test(s);
    }

Result:

![screenshot](https://cloud.githubusercontent.com/assets/1659374/13261006/710d44f4-da5e-11e5-9e55-49fefca87bf8.png)

**Comment by 50Wliu** [comment]
This is a duplicate of #78 - feel free to subscribe there for updates.
