### ISSUE TITLE
Add extra spacing on auto-closed `()` and `{}`

### ISSUE THREAD

**Issue by NAlexPear** [atom/bracket-matcher#216]
The style guide for a codebase I'm working on requires extra spaces between parens and curly braces. For example:
```javascript
//spaced
var newView = Backbone.View.extend( {
  "template": _.template ( tmpl )
} );

//standard
var newView = Backbone.View.extend({
  "template": _.template (tmpl)
});
```
I'd like to be able to add those spaces automatically on auto-completion, since I know that I'll need it every time. Could this possibly be added or a feature?

**Comment by trueter** [comment]
I would very much like to see this, too.

**Comment by 50Wliu** [comment]
This is a duplicate of #16 - feel free to subscribe there for updates.
