### ISSUE TITLE
Bracket Highlighting

### ISSUE THREAD

**Issue by JLCCI** [atom/bracket-matcher#225]
First of all thanks for the amazing work with the package.

Not really an issue but rather a comment. I found an amazing package that makes the bracket highlighting look much better and overall fit with how atom looks.

https://github.com/pvorona/atom-bracket-highlight

Perhaps it would be a good idea to merge it with the stock bracket package?

**Comment by slang800** [comment]
Changes to the default styles should probably be requested in https://github.com/atom/one-dark-syntax. Bracket-matcher handles the logic behind matching brackets and comes with very few CSS rules (since additional rules would need to be reset in every theme that doesn't want animated brackets).

**Comment by 50Wliu** [comment]
Thanks @slang800.
