### ISSUE TITLE
Matches parens inside string and regexp literals

### ISSUE THREAD

**Issue by maxbucknell** [atom/bracket-matcher#23]
Currently, the bracket-matcher will tell me that the opposite paren inside this function call is inside a string.

![image](https://cloud.githubusercontent.com/assets/1707318/2579673/563f99ba-b9a4-11e3-80dd-460221519a8f.png)

The expected behaviour is that this is correct.

**Comment by tony612** [comment]
Any progress for this issue?

**Comment by 50Wliu** [comment]
Closing this in favor of #78.
