### ISSUE TITLE
bracket selection with multiple cursors 

### ISSUE THREAD

**Issue by acarl005** [atom/bracket-matcher#231]
It would be nice if cmd+ctrl+m would select multiple things when triggered when there are multiple cursors.

**Comment by SandSnip3r** [comment]
Right, each cursor should expand to it's given scope. If multiple cursors share a scope, they become a single selection.

**Comment by tnrich** [comment]
Please please please someone fix this one!

**Comment by 50Wliu** [comment]
This is a duplicate of #192 - feel free to subscribe there for updates.

@tnrich Feel free to send a PR fixing this issue.
