### ISSUE TITLE
Continue expanding selection of brackets

### ISSUE THREAD

**Issue by chamini2** [atom/bracket-matcher#233]
In a case like

`[ { a: (2 |+ 3) * 4 }, { a: (2 - 4) / 4 } ]`

Where the cursor is just before the `+` (it's the `|`), using `select-inside-brackets` should (as it does) select the `2 + 3`. Selection marked with ~~*strikethrough*~~.

`[ { a: (`~~`2 + 3`~~`) * 4 }, { a: (2 - 4) / 4 } ]`

But then, using `select-inside-brackets` again would expand the selection further until the `{}`:

`[ {`~~` a: (2 + 3) * 4 `~~`}, { a: (2 - 4) / 4 } ]`

And using it once again would expand until the `[]`:

`[`~~` { a: (2 + 3) * 4 }, { a: (2 - 4) / 4 } `~~`]`

**Comment by chamini2** [comment]
I think this is a duplicate of #74, and fixed by #167.

**Comment by 50Wliu** [comment]
Thanks @chamini2.
