### ISSUE TITLE
problem with matching single quotes and backtick

### ISSUE THREAD

**Issue by vasanthaganeshk** [atom/bracket-matcher#236]
if I disable Autocomplete bracket then it also disables matching brackets and matching double quotes. I want matching brackets and matching double quotes but not matching single quotes and matching backticks, this would help in typing Lisp in Atom.

**Comment by potto007** [comment]
Hi @vasanthaganeshk - I submitted a pull request yesterday that addresses this. When you get a chance, please try it out and see if it satisfies your needs.

**Comment by vasanthaganeshk** [comment]
@potto007 thanks!

**Comment by 50Wliu** [comment]
Closing in favor of #121.
