### ISSUE TITLE
Bracket-Matcher does not work 

### ISSUE THREAD

**Issue by greensleeves01** [atom/bracket-matcher#245]
Fresh install of Atom v. 1.10.1 on a Win7 SP1 laptop.  Confirmed in packages that bracket-matcher is in fact installed.  Bracket-matcher is enabled, however, it does not auto close brackets, quotes, or anything else bracket-matcher is supposed to close.  Is this a bug?  What am I missing?  Very very very frustrating.  This should work by default is my understanding and yet it does not.

**Comment by 50Wliu** [comment]
Just to confirm: does this also happen in safe mode (`atom --safe`)?

**Comment by 50Wliu** [comment]
Closing until requested information is provided.

**Comment by greensleeves01** [comment]
So, essentially,  and to recap, you are suggesting that above referenced issue will not happen if user only uses software in safe mode?  Atom should be used in safe mode only in order for the bracket-matcher to function?

**Comment by 50Wliu** [comment]
No, I am merely asking *if* your problem still exists in safe mode.  This is so we can eliminate the possibility of community packages interfering with bracket-matcher functionalities.

**Comment by greensleeves01** [comment]
That would be affirmative.  Bracket-match does not function in safe mode either.

**Comment by 50Wliu** [comment]
Ok, thanks for the update.  Some other questions: if you go into the bracket-matcher settings, does it look like the correct settings are enabled?  Are you using an international keyboard layout?

**Comment by potto007** [comment]
Very strange. The current version, 0.82.2, works fine for me on all my systems. I'm surprised that it does not work in safe mode, either. If it isn't an interaction problem with non-core packages, then I would guess it to be an issue that Atom or Electron is having with nodejs on your system?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/bracket-matcher/issues/245#issuecomment-249425148. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
