### ISSUE TITLE
Brace Matching Peek Enhancement

### ISSUE THREAD

**Issue by orthros** [atom/bracket-matcher#248]
# Brace Matching Peek Enhancement
A feature I have found invaluable in other editors (in particular Visual Studio) is the ability to mouse over a brace, and be given a tooltip "peek" of what is on the other side of that brace:

The general workflow for this should be of form:

1. User mouses over a closing brace
2. A tooltip of the statement or declaration that precedes the opening brace is presented above or below the mouse

### Simple if statement:
![image](https://cloud.githubusercontent.com/assets/7820716/18684818/395e5e94-7f3b-11e6-8402-470898e47065.png)

### Class declaration:
![image](https://cloud.githubusercontent.com/assets/7820716/18684910/974c3044-7f3b-11e6-88fe-07a2b6b3fce0.png)

### Function Declaration:
![image](https://cloud.githubusercontent.com/assets/7820716/18684992/dd2b46c2-7f3b-11e6-9d0f-8f7828fde59a.png)

If this is not the proper place for this enhancement, I'd greatly appreciate any direction to where I should put it (or if I should write my own package 😄  ).

**Comment by 50Wliu** [comment]
> or if I should write my own package 😄

That would be a great idea!  If you need help with that, I would suggest posting on [Discuss](https://discuss.atom.io).

**Comment by orthros** [comment]
Fantastic, thanks!
