### ISSUE TITLE
Can't find directory with config files of bracket-matcher

### ISSUE THREAD

**Issue by sanzinken** [atom/bracket-matcher#278]
Hi, there! I want configure by myself, some view options in bracket-matcher. But I can't find in $HOME/.atom/packages/ any directory with config files of bracket-matcher. I tried to find it with `$ locate bracket-matcher`, but found only some files in .atom/compile-cache/less/.../content/.../bracket-matcher.atom-text-editor.json. But in atom editor - Settings - packages - Core Packages it included. I don't understand anything how it can be, but it is... How I can fix it? 

My OS: Linux Mint 18 sarah
Atom version: 1.14.4

**Comment by 50Wliu** [comment]
`~/.atom/config.cson`.
