### ISSUE TITLE
Add command to select matching bracket

### ISSUE THREAD

**Issue by diegoandresalvarez** [atom/bracket-matcher#280]
I would like to suggest a new functionality:

I am translating a code from MATLAB to JULIA

MATLAB uses ( ) to index arrays, while JULIA does use [ ]

What about a functionality that allows me to change one bracket for the other? 

For example I have

x(idx, :)

I put the cursor before the (  so that the ( is highlighted together with the )
I hit my magic shortcut, lets say Ctrl+Alt+C and hit [

Then atom automatically replaces the ( ) for [ ] and now my text is

x[idx, :]

**Comment by cortner** [comment]
I have *precisely* the same use-case :)

**Comment by 50Wliu** [comment]
This would need a `bracket-matcher:select-matching-bracket` command.

**Comment by zach-nervana** [comment]
$50 bounty at https://www.bountysource.com/issues/43914367-add-command-to-select-matching-bracket
