### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by glenrage** [atom/bracket-matcher#282]
You have the core package "bracket-matcher" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/Users/galangpham/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/Users/galangpham/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Users/galangpham/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Users/galangpham/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:32)
```

**Comment by 50Wliu** [comment]
You have the core package "bracket-matcher" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
