### ISSUE TITLE
`MatchManager` is not destroyed when the associated editor gets destroyed

### ISSUE THREAD

**Issue by as-cii** [atom/bracket-matcher#283]
They are created [here](https://github.com/atom/bracket-matcher/blob/4343236b9ad0ebbd2975af044a4da99c251bda3a/lib/main.coffee#L9), but they are never destroyed. This is causing a memory leak, as you can notice in the following heap snapshot:

![screen shot 2017-04-24 at 16 00 02](https://cloud.githubusercontent.com/assets/482957/25340794/1a55d4de-2907-11e7-85a7-8273dd73f9d6.png)

/cc: @iolsen

**Comment by driskell** [comment]
Seeing this also.

Also seeing that if you just opened a bracket and it was autocompleted, a DisplayMarker is leaking in `this.bracketMarkers` I think.

**Comment by driskell** [comment]
I raised #284 which I think works. The bracketMarkers is false positive as it should release once the subscriptions are gone.

**Comment by driskell** [comment]
@as-cii Any possibility of looking at this issue and associated pull request soon? Happy to help where needed.

I often work on many projects with many files being opened and closed to diagnose issues and this issue very quickly exhausts my memory on a daily basis with Atom Helper consuming beyond 1.8GB.
