### ISSUE TITLE
Misordered »Autocomplete Characters«

### ISSUE THREAD

**Issue by Semnodime** [atom/bracket-matcher#286]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The defaut value for breaket matching needs correction.

### Steps to Reproduce

1. Open settings
2. Navigate to the installed bracket-matcher
3. View the default of »Autocomplete Characters«

**Expected behavior:**

» is matching « and › is matching ‹

**Actual behavior:**

« is matching » and ‹ is matching ›

**Reproduces how often:**

100%

### Versions
atom --version
- Atom    : 1.16.0
- Electron: 1.3.13
- Chrome  : 52.0.2743.82
- Node    : 6.5.0

apm --version
- apm  1.16.1
- npm  3.10.5
- node 6.9.5 ia3
- python 3.5.3
- git 2.10.0.win
- visual studio

### Additional Information

Im neo2 fan and therefore discovered the problem when tring »« in the editor…

**Comment by 50Wliu** [comment]
According to https://en.wikipedia.org/wiki/Guillemet, «» is far more common than »«.  I think we'll be supporting the more common use case especially since this setting is configurable.
