### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by mateddy** [atom/bracket-matcher#292]
[Enter steps to reproduce:]

(added by @rsese):

1. mkdir test; cd test
2. `atom --safe .`
3. Create a file `test.html` with this content (it's just the `html` snippet`):

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>
```

4. Quit Atom.
5. Delete or move `test.html`.
6. `atom --safe .`

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\AMA\AppData\Local\atom\app-1.19.0-beta0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:55

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/tokenized-buffer.js:252:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/tokenized-buffer.js:246:27)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/tokenized-buffer.js:206:32
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -0:14 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.26 
atom-bootstrap4 1.4.0 
atom-overtype-mode 0.3.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autohide-tree-view 0.25.1 
browser-plus 0.0.91 
color-picker 2.2.5 
docblockr 0.10.3 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.7 
filesize 3.0.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
language-apache 1.7.0 
language-latex 1.0.0 
language-openscad 0.4.3 
latex 0.44.0 
line-count-status 0.0.3 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
open-in-browsers 0.0.30 
open-recent 5.0.0 
open-unsupported-files 1.0.20 
pigments 0.39.1 
project-manager 3.3.5 
remote-edit2 3.0.0 
remote-sync 4.1.5 
script 3.15.0 
split-diff 1.4.1 
sync-settings 0.8.2 
tabs-to-spaces 1.0.3 
tree-view-open-files 0.3.0 
tree-view-sort 0.7.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by timfallmk** [comment]
@rsese This appears related to https://github.com/atom/bracket-matcher/issues/281 

Repro:
Open atom or a file that has brackets (in my case a yaml).

Also happens on startup with `safe` mode.

**Comment by rsese** [comment]
Thanks @timfallmk - I tried to open this random Atom JavaScript file:

https://github.com/atom/atom/blob/c1c0e7e921b7125aa8afbb652b238694d3b3cd31/src/atom-paths.js

And it worked ok on Atom `1.19.0-beta1` and macOS 10.12.5.  It sounds like any file with brackets throws this error for you?  Does the above file cause the error for you?  If not, can you share a file that does so I can give it a try?

**Comment by timfallmk** [comment]
@rsese I checked the file above in a blank project workspace and **didn't** get the error. I am still seeing the error in the large projects I actually work on, but I'll try and narrow down a specific file that throws it.

Is there a good way to get a trace of which file is causing the error? The stack that the package spits out doesn't seem to contain actual file paths.

**Comment by timfallmk** [comment]
Quick update, I re-opened an old project that doesn't contain any javascript and it didn't error out. That would narrow down the candidates to javascript related files.

**Comment by vvs** [comment]
I opened Atom today (with my JS-related project) and got exactly this error as well. Not sure what actually changed, there were no errors yesterday. Windows 10 x64, Atom 1.19.0-beta1.

**Comment by vvs** [comment]
Some more info. The error is reproducible 100%. Starting is safe mode does not resolve the problem.
The only workaround for now is to completely disable the bracket-matcher package.

**Comment by rsese** [comment]
@vvs @timfallmk - any chance either of you have a public project that you can share that causes the error?  Also, I wonder if this is related to some of the recent updates to bracket-matcher (e.g. https://github.com/atom/bracket-matcher/pull/273) that's in the 1.19 beta.  @timfallmk I don't think you mentioned what OS you're on, do you happen to be on macOS where you're running stable and beta side-by-side?  If so, can you confirm if you can reproduce on 1.18.0?

**Comment by vvs** [comment]
OK, I managed to create a fully-reproducible use-case.

1. Clone `atom/bracket-matcher` repo (this one).
2. `cd bracket-matcher`
3. `atom .`
4. open `lib/tag-finder.coffee`
5. close Atom
6. delete `lib/tag-finder.coffee` file
7. launch atom, and see the error/exception dialog.

**Comment by nyaaao** [comment]
I'm getting this when I have an open tab for a non-existent (moved/deleted/renamed etc) file
[Enter steps to reproduce:]

1. start new project
2. create and save new file
3. close window
4. delete or rename the file
5. re-open project

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/usr/share/atom-beta/resources/app/src/workspace.js:717:15)
    at Object.activate (/usr/share/atom-beta/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:253:25)
    at /usr/share/atom-beta/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app/src/package.js:99:21)
    at /usr/share/atom-beta/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom-beta/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom-beta/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom-beta/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom-beta/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom-beta/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:58 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-nord-atom-syntax-accessibility-custom-comment-contrast)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-dark-fusion-syntax 2.2.0 
atom-handlebars 1.3.0 
atom-snippets 0.1.1 
base16-ocean-dark-spacegray 0.13.0 
blame 0.12.0 
busy-signal 1.4.3 
dark-flat-ui 1.2.4 
diff-pane 0.3.0 
editorconfig 2.2.2 
file-icons 2.1.7 
gaia-dark-syntax 2.0.0 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
graphite-ui 0.15.1 
grunt-runner 0.14.0 
intentions 1.1.2 
jsformat 0.9.3 
language-gitignore 0.3.0 
language-pgsql 0.2.3 
language-volt 0.2.2 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
mocha-test-runner 1.0.0 
new-moon-atom-syntax 2.0.9 
no-caffeine-syntax 0.18.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
platformio-ide-terminal 2.5.1 
project-manager 3.3.5 
semantic-ui 1.0.9 
seti-ui 1.8.0 
sort-lines 0.14.0 
spacegray-dark-ui 0.13.0 
split-diff 1.4.3 
symbol-gen 1.3.1 
sync-settings 0.8.2 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
uuidgen 1.2.1 
```

**Comment by rsese** [comment]
Great thanks @vvs, I'll give that a try when I get a chance.

**Comment by timfallmk** [comment]
@rsese et al. Note I'm no longer seeing this with 1.19.0-beta2. It may have been cleared up by the decorator fix.

**Comment by rsese** [comment]
So odd, I wasn't able to reproduce with the specific repo and steps you detailed [above](https://github.com/atom/bracket-matcher/issues/292#issuecomment-310831043) @vvs but creating and deleting just a test file as described by @nyaaao in their [comment](https://github.com/atom/bracket-matcher/issues/292#issuecomment-310898956) I was able to reproduce.  I did note however that the test file I used was an HTML file, I couldn't reproduce with just a Markdown file for example:

1. mkdir test; cd test
2. `atom --safe .`
3. Create a file `test.html` with this content (it's just the `html` snippet`):

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
     <a href="" />
  </body>
</html>
```

4. Quit Atom.
5. Delete or move `test.html`.
6. `atom --safe .`

I also updated to 1.19.0-beta2 and I still get the error with these steps.  I actually get 2 errors, one that points here and another that points to #281 which you already commented on @timfallmk.  I'll go ahead and re-open that one since I can reproduce.

I did also note that I can't reproduce in 1.18.0 so I'll tag this as a regression as well - let me know if y'all see any differently.

**Comment by Raindeer44** [comment]
This is popping up for me with Atom 1.19.0-beta2 x64 on Windows 7 Enterprise. I get it after switching Git branches with tabs open for files which don't exist on the new branch. This is happening for Java, GSP and JavaScript files. I tested with `--safe` but not with Atom 1.18.0.

Same as @rsese noted, I get errors pointing to both this issue and to #281.

**Comment by Stanzilla** [comment]
Yup, can confirm it happens when you open files that no longer exist.

**Comment by bradennapier** [comment]
Why is this closed when it is still an issue?  I am on latest atom and getting this error - seems to be as pointed out -- when you have a file open in your tabs that is no longer in existence.  

This should be fixed.

**Comment by MaryAddams** [comment]
I was getting the error, but then I tried to install the package. It seems to be working now.

**Comment by Ben3eeE** [comment]
@bradennapier This issue is closed because the fix has been merged to master. The fix for this will be released with the next hotfix release. We close our issues when they are fixed and merged on master and not when they are released.

**Comment by bradennapier** [comment]
Thanks @Ben3eeE
