### ISSUE TITLE
Feature request: Go to matching closed bracket AKA Fly Mode

### ISSUE THREAD

**Issue by predragnikolic** [atom/bracket-matcher#300]
### Description
I wont to quickly go to the closed bracket. This is not the same as ctrl+m. 

### Steps to Reproduce
CURSOR is |

input:
 {
     hello()|;
     world();
 }

 (press } at |)

**Expected behavior:** 
 output:
 {
     hello();
     world();
 }|

**Actual behavior:** 
output:
 {
     hello()}|;
     world();
 }

**Reproduces how often:** 
Always
### Versions

bracket-matcher 0.85.5

### Additional Information
This idea come from a plugin for vim [auto-pairs](https://github.com/jiangmiao/auto-pairs). It has a feature called fly mode, which is disabled by default, but I think is very useful.

**Comment by waknin** [comment]
Would also appreciate this feature! It adds a lot of productivity and helps on not relying simply in indentation.
