### ISSUE TITLE
bracket-matcher freezes opening html file 

### ISSUE THREAD

**Issue by ungb** [atom/bracket-matcher#303]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

bracket-matcher freezes opening html file 

### Steps to Reproduce

1. clone bracket-matcher 
2. checkout `3a557719820bc151a7d09c8440d2c4f05b39fd80`
3. `apm install && apm link` bracket matcher
4. Save the following code to `index.html` file and open it on atom:
```html
<div style="display: flex; width: 500px; height: 100px; background: blue">
  <div style="min-width: 1em; background: red">

    <div style="background: yellow; position: absolute; left: 0; right: 0; height: 20px" />

  </div>

</div>

```

**Expected behavior:** [What you expect to happen]
Should load up atom quickly and work
**Actual behavior:** [What actually happens]
Atom freezes up.  

___NOTE: 
Looks like this is caused by https://github.com/atom/bracket-matcher/pull/257___

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

```

This is related to the change in https://github.com/atom/bracket-matcher/pull/257 more than the version of Atom.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ungb** [comment]
⬇️ bracket-matcher to 0.87.0 on master.

**Comment by 50Wliu** [comment]
There's some catastrophic backtracking going on when the tag pattern regex tries to match this line: `<div style="background: yellow; position: absolute; left: 0; right: 0; height: 20px" />`.  Trying to figure out where in the regex and why it's happening.
