### ISSUE TITLE
Only One Tag is Highlighting

### ISSUE THREAD

**Issue by superjoefly** [atom/bracket-matcher#329]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Only one tag is highlighting when I select a tag. This happens with brackets as well as HTML tags. Up until recently, both tags would highlight.

### Steps to Reproduce

1. Select a tag and view the highlighting of the opening and closing tags. Only one is highlighting.

**Expected behavior:**

Expected both the opening and closing tags to be highlighted.

**Actual behavior:**

Only one tag, the one NOT selected, highlights.

**Reproduces how often:**

100%

### Versions

Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

### Additional Information

Please, let me know if there is anything else I can provide to help with the issue.

**Comment by rsese** [comment]
Thanks for the report!  Can you share some example code that reproduces this behavior?  Wondering if it's the same issue as https://github.com/atom/bracket-matcher/issues/333.

**Comment by superjoefly** [comment]
@rsese 

It's similar to #333 but not exactly the same...

If I place the cursor next to an opening tag, the closing tag will highlight. If I place the cursor next to the closing tag, the opening tag highlights. However, the opening and closing tags do not stay highlighted at the same time.

Note: this happens in all files containing html.

Here are some images. I hope they are helpful:

![example](https://user-images.githubusercontent.com/22858922/33693227-e15b63ec-daae-11e7-9493-e4b7ba98b8ae.png)

![example2](https://user-images.githubusercontent.com/22858922/33693234-e9c53ee0-daae-11e7-8432-b14331ab8ed8.png)

**Comment by rsese** [comment]
I had a chance to test on 1.21.2 with Ubuntu 16.04 but couldn't reproduce.  I also tried with the latest stable version (1.23.2) and couldn't reproduce either - can you install the latest version and let me know if you still see this behavior in safe mode?

**Comment by superjoefly** [comment]
Okay...did some testing and it has something to do with the styles defined in my styles.less.
Thanks so much for your help :-)

**Comment by rsese** [comment]
Ahhh great, glad you found the cause!

**Comment by jibsen** [comment]
I think it might be a bug that the current line background is drawn on top of the bracket underline. It means that in any theme with an opaque current line background, the bracket underline will not be visible on the current line.
