### ISSUE TITLE
Matching HTML tags not highlighted properly when one of them is multi-line

### ISSUE THREAD

**Issue by iagoqo** [atom/bracket-matcher#333]
When one of the HTML tags is multi-line some matching brackets are not highlighted properly, highlighting one of a different element or none at all. The behaviour is the same in safe mode.

Here is a simple example that shows this. On longer files the issue spreads until the end.

![atom](https://user-images.githubusercontent.com/1913495/33277383-4af2f5ac-d390-11e7-9cc9-ae20741c14e7.png)

Code in the examples:

    <div>
      <div class="test"
        title="test"
      >
        <div>test</div>
      </div>
    </div>

I don't remember this happening a few months ago, so the bug may have appeared on one of the latest releases.

bracket-matcher version: 0.88.0
atom version: 1.22.1
OS: Windows 10

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce the behavior you're seeing on macOS 10.12.6 with Atom 1.22.0, I used this snippet:

```html
<html>
<body>
<div class="">
  <div class=""
       style="">
    Atom 1.21.2
  </div>
</div>

</body>
</html>
```

On 1.22.0:

![bracket-match-1 22 0](https://user-images.githubusercontent.com/734194/33635666-77939c98-d9de-11e7-8902-91d2261dd765.gif)

And see that it worked ok in 1.21.2:

![bracket-match-1 21 2](https://user-images.githubusercontent.com/734194/33635672-7dec2a24-d9de-11e7-93a7-06d91e7bd060.gif)
