### ISSUE TITLE
No settings and cannot update this package...

### ISSUE THREAD

**Issue by ffpyguy** [atom/bracket-matcher#342]
I have the latest version of atom 1.23.3 x64 on Win7.
bracket-matcher 0.88.0 WILL NOT UPDATE..?? why not? how do i do it?
and there are no settings at all for the package... just says No README, lol?
i have to go back to sublime text cuz i cant turn off the automatic quotes swallowing, like when i select some text and press the quote key it surrounds my text in quotes, i dont want that happening, really annoying.

thank you for ur support!

btw, disabling the package didnt help, i tried it, as if something else is controlling the quote-wrapping thingy...?

**Comment by rsese** [comment]
> bracket-matcher 0.88.0 WILL NOT UPDATE..?? why not? how do i do it?

bracket-matcher is a core package so is updated when a new version of  Atom is released.  Do you happen to have bracket-matcher installed as a community package?  You can check with:

```
apm list --installed --packages
```

If bracket-matcher shows up there, uninstall it with `apm uninstall bracket-matcher`.
