### ISSUE TITLE
Auto-closing angle bracket is inconvenient.  Can't disable.

### ISSUE THREAD

**Issue by whmountains** [atom/bracket-matcher#354]
Recently Atom started auto-closing the `<` character.

Steps to reproduce: type the `<`.
What I'm seeing: `<` gets replaced with `<>`.

This is probably great for HTML developers, but it is super annoying when actually programming because it messes up the `<`, `>`, `<=`, and `>=` operators.  Please consider not enabling globally by default.  Selectively enabling it only for XML and HTML would be fine, however.

I still haven't figured out how to disable this correctly, since Atom seems to ignore the "Autocomplete Characters" list.  I've tried removing the angle brackets from that list but it still adds the extra `>` whenever I type `<`.  Only way I've figured out how to stop it is to uncheck "Autocomplete Brackets", but that disables it for all characters, not just the angle bracket.

To be precise, angle brackets are still getting auto-completed under the following configuration:

![screen shot 2018-07-25 at 10 32 08 am](https://user-images.githubusercontent.com/8680147/43210920-01c3eeb8-8ff6-11e8-92d8-c386cb26020e.png)

**Comment by rsese** [comment]
Thanks for the report! Can you add some of the issue template information? The information in the template is super helpful for us when triaging issues - for example, do you see this behavior in safe mode?  What version of Atom are you running and what operating system?

> Steps to reproduce: type the <.
> What I'm seeing: < gets replaced with <>.

Is this with a particular file type?  With these steps I can't reproduce with Atom 1.28.2 on macOS 10.12.6:

1.  `atom --safe`
2. Create a new file (so a plain text file)
3. Type <kbd><</kbd>

`<` isn't replace with `<>` at this point for me.  Also tried in a JavaScript file.

I'm using all the default settings:

![bracket-match-settings](https://github-slack.s3.amazonaws.com/monosnap/Settings__githubatom_2018-07-25_17-41-39.png)

> I've tried removing the angle brackets from that list but it still adds the extra > whenever I type <.

I think those aren't angle brackets in the `Autocomplete Characters` field, those are [angle quotes](https://en.wikipedia.org/wiki/Guillemet).

**Comment by alkahestazoth** [comment]
I also encountered the same problem and the conditions under which it happened became somewhat apparent.
The setting of "Autocomplete Characters" will be completely ignored when using some grammar highlight package such as language-rust.
With Plain Text and other grammars, the problem may not occur.
