### ISSUE TITLE
Tag matching doesn't work in HTML with tree-sitter enabled

### ISSUE THREAD

**Issue by oueryemchi** [atom/bracket-matcher#355]
*Edit by @rsese to add issue template details*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Bracket matching in HTML doesn't work with tree-sitter enabled.

### Steps to Reproduce

1. Enable tree-sitter `Settings > Core > Use Tree Sitter Parsers`
2. Create and save a file `test.html` with the `html` snippet content:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>
```

3. Click in the `<body>` tag.

**Expected behavior:** [What you expect to happen]

Expect the `<\body>` tag to be highlighted.

**Actual behavior:** [What actually happens]

The `<\body>` tag isn't highlighted.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
$ atom-nightly  -v
Atom    : 1.31.0-nightly3
Electron: 2.0.6
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

macOS 10.12.6

### Additional Information

If you disable tree-sitter, the tag matching works.

---

always worked in all files. after updating Atom and packages 2 days ago (done on 2d of August 2018), Matcher stopped working in plain HTML files.

I disabled all packages and left on the core ones, still not working..

**Comment by rsese** [comment]
Thanks for the report - I think this is an issue with tree-sitter, do you have tree-sitter enabled @oueryemchi (`Settings > Core > Use Tree Sitter Parsers`)? 

Also, what version of Atom are you running (`atom -v`) and what operating system?  Please use the issue template, the information in the template is super helpful for us when triaging issues.

**Comment by oueryemchi** [comment]
Indeed! you're the man! that was the culprit and you saved the day ;)

Thanks much!

_For info sake: I am on Win 10 - 64Bit (updated to latest) and Atom version is 1.29.0_

**Comment by rsese** [comment]
Going to go ahead and re-open just to confirm this is fixed - /cc @maxbrunsfeld @queerviolet.  @maxbrunsfeld we talked about this a bit ago and I think you mentioned this will be fixed and that I should ping you in an issue for the behavior just for tracking?

**Comment by ahallicks** [comment]
Just to note on this that it works for me in normal HTML documents but not in documents that don't have an opening `<html>` tag.

We use HTML includes where I work and the includes are just blocks of HTML. With the tree sitting enabled tag matching doesn't work on these includes, but does on any normal HTML document.

This is in Atom v1.33.0-beta1.

**Comment by Ben3eeE** [comment]
This is also an issue for jsx.

**Comment by liquidmetalrob** [comment]
> Just to note on this that it works for me in normal HTML documents but not in documents that don't have an opening `<html>` tag.
> 
> We use HTML includes where I work and the includes are just blocks of HTML. With the tree sitting enabled tag matching doesn't work on these includes, but does on any normal HTML document.
> 
> This is in Atom v1.33.0-beta1.

Thanks! That saved my day. I didn't realise I needed to have the opening html tag.
