### ISSUE TITLE
Not matching < >  greater than less than

### ISSUE THREAD

**Issue by cyphunk** [atom/bracket-matcher#369]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Selecting text in a .txt file and then pressing ``(`` would normall cause the selected text to be encased in ``()``. However, when pressing ``<`` the expected result of encasing the selected text or word (including word not split between lines) does not encase the selection with ``< >``

### Steps to Reproduce

1. open a txt or .md in safe mode atom
2. type a word, select word, press ``<``

**Expected behavior:** selected word is encased in ``< >`` when selecting and pressing ``<``

**Actual behavior:** selected word is deleted and replaced with ``<`` 

**Reproduces how often:** always

### Versions
```
Atom    : 1.32.1
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by rsese** [comment]
Thanks for reaching out!  You can do this by adding "<>" to `Settings > Packages > Bracket Matcher > Autocomplete Characters`.  If that doesn't help let me know!
