### ISSUE TITLE
Highlighting feature request

### ISSUE THREAD

**Issue by andersennl** [atom/bracket-matcher#47]
First of all, thanks a lot for this really useful package. While using it for some time now, I've noticed that it would be nice to not only see a underline marking the matching bracket, but a "block hightlight", surrounding the whole bracket in a maybe yellowish color would be  more noticeable. 

Would it be possible to add some kind of switch in the package setings to switch between these two display types? Thanks again!

**Comment by 50Wliu** [comment]
This is a duplicate of #30 - feel free to subscribe there for updates.
