### ISSUE TITLE
Can't write symbol ">"

### ISSUE THREAD

**Issue by vanja988** [atom/bracket-matcher#54]
When I try to write the symbol ">" using Ctrl-Alt-. it closes the tag without writing the symbol, like this:

`<div class="container"</div>`

**Comment by LouisTakePILLz** [comment]
I second that; it occurs on my end as well.
It should also be worth noting that I'm on the "French (Canada) Canadian Multilingual Standard" keyboard set, which maps the "< >" chevrons mapped to `RALT+,` and `RALT+.`

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom-keymap#35.  Please try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.
