### ISSUE TITLE
cannot open square bracket

### ISSUE THREAD

**Issue by hrvoje-grabusic** [atom/bracket-matcher#69]
Can't open square bracket [ when pressing ctrl+alt+f

On Croatian keyboard the left bracket is on the f key.

**Comment by VjeraTurk** [comment]
2016. still not fixed

**Comment by glowdemon1** [comment]
A solution for my Belgian (nl_be) layout was to add the following code in the keymap (keymap.cson)
`'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-]': 'unset!'`

**Comment by ericpar** [comment]
I have the same problem using a French Canadian keyboard layout.

**Comment by rdemeyer** [comment]
The solution from @glowdemon1 works for me (layout fr_be).

**Comment by philippe99** [comment]
Works also for me; thanks @glowdemon1

**Comment by koracIO** [comment]
Still having trouble @hrvoje-grabusic ?
I found this solution working for me, on my croatian keyboard:
'.platform-win32 .editor':
 'ctrl-alt-f': 'native!'

'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-f': 'unset!'

**Comment by hrvoje-grabusic** [comment]
i am using visual studio code now.
It is interesting that vscode also had the same problem but they fixed it within a couple of days.
Since they open sourced it perphaps atom can copy their sollution.

**Comment by koracIO** [comment]
Would be nice if they did that.

**Comment by Smailowska** [comment]
@koracIO This helped. Thanks a lot!

**Comment by DannyBiker** [comment]
Thank you @glowdemon1 for the workaround. It would be nice to get a proper fix though...

**Comment by 50Wliu** [comment]
@DannyBiker This should be fixed starting in Atom 1.12.0.
