### ISSUE TITLE
Clashes with Auto-indent

### ISSUE THREAD

**Issue by benogle** [atom/bracket-matcher#7]
![bad_brace_behavior](https://f.cloud.github.com/assets/285675/2289420/c3cbc988-a007-11e3-9117-72bbbd040d86.gif)

Auto-indent only works when line ends in open curly-brane, which is checked before the event mutates the text. At that time, the pesky close brace is in the way.

Qt Creator, for example, does _not_ automatically add curly braces. Instead, it appears to  check for a carrier return pressed right after an open curly brace and, in that case, it adds the matching close brace at the right place. That seems like a saner piece of behavior.

(I first filed this under general Atom feedback, but now I think this might be better off done here. Sorry for the noise.)

**Comment by rustedwolf** [comment]
It's not working anymore while working with Less files. :( The behaviour is the same as described in post beginning.
bracket-matcher ver.: 0.71.0
Atom ver.: 0.184.0

**Comment by Yahosh** [comment]
Yeah, doesn't seem to work for me while writing js.

bracket-matcher - 0.71.0
atom - 0.186.0

**Comment by mlmorg** [comment]
@Yahosh knows what's up

**Comment by rustedwolf** [comment]
@Yahosh, that's weird, I'm not having problems with js. Although my version's bit older.
Perhaps it's might be plugin conflict related?

**Comment by Yahosh** [comment]
Oops, you're right @rustedwolf . I had the plugin enabled but accidentally turned off Auto Indent in the general settings while I was making some other changes. Everything's working, including LESS for me.

**Comment by rustedwolf** [comment]
@Yahosh, since LESS works on your Atom build, that means I have to check with my settings. Perhaps, and Atom upgrade will do that.

**Comment by jakegavin** [comment]
![autoindent](https://cloud.githubusercontent.com/assets/5965895/10834249/f69dbb46-7e54-11e5-8378-1a20f9a34a59.gif)

This should be indenting line 3, right?
I'm new to Atom so maybe I have something configured wrong but I have the global setting for Auto Indent enabled. Language is set to ruby. 

Atom 1.1.0
Bracket Matcher 0.78.0

**Comment by sompylasar** [comment]
I made a package that indents empty lines using the Atom's internal auto-indent when you move the cursor, and cleans up trailing spaces from empty lines when the cursor moves to another place. Works for any language.

Please feel free to try and leave feedback!

https://github.com/sompylasar/atom-cursor-indent

<img src="https://cloud.githubusercontent.com/assets/498274/12710012/0c317764-c8c3-11e5-8c82-1cc832e69952.gif" />
