### ISSUE TITLE
Bracket Matcher has stopped closing DIV tags

### ISSUE THREAD

**Issue by ghost** [atom/bracket-matcher#79]
For some reason, it won't close `<div>` anymore in my particular HTML file. Pretty much any other HTML tag, it will close (`Cmd-Opt-.`). If there's any way I can help debug, I'm game!

**Comment by rsese** [comment]
Closing in favor of https://github.com/atom/bracket-matcher/issues/320 but I'll copy over @fauxparse's comment since it has interesting details.
