### ISSUE TITLE
Backslash prevents pair autocompletion

### ISSUE THREAD

**Issue by SahilMadan** [atom/bracket-matcher#80]
Firstly, apologies for not being able to make a gif of the issue!

For hello_world.c, if I type the following:

> printf("

A secondary (closing) quotation mark is automatically inserted (along with a closing bracket). I.e.

> printf("")   // The ") appear automatically

. If I type the following...

> printf("Hello World");

As I type the closing quotation mark and bracket, the ones inserted automatically by Atom are replaced as I type over them.

However, if I type the following...

> printf("Hello World\n"

The secondary quotation mark is not replaced or typed over. Instead, another quotation mark is inserted. This results in the following...

> printf("Hello World\n"")

The expected behaviour (as also seen in Sublime Text) would be to behave consistently, and replace the automatically inserted closing quotation mark as I type over it.

The use of a escape character right before the closing quotation mark causes this problem to occur. I was able to cause this to occur with \t, \n, and \b. If I type a space between the escape character and the closing quotation mark, the error does not occur. I.e.

> printf("Hello world\n ")

![Animated GIF](http://i.imgur.com/DaZkgtj.gif)

**Comment by fredojones** [comment]
This behaviour is really annoying, has any progress been made on this? I can imagine that a tonne of people would be affected by it

**Comment by 190n** [comment]
+1

**Comment by nerssi** [comment]
This is such an aggravating and frequently encountered bug, at least for me. Is anyone aware of any way to circumvent this issue in the meanwhile until it is fixed, via a package perhaps?

**Comment by kebno** [comment]
![out](https://cloud.githubusercontent.com/assets/1569364/11571048/4429ac74-99af-11e5-9dcd-efba44f449db.gif)

I am bothered by this every day.
Atom 1.2.4, OS X 10.11.1

**Comment by WalterGR** [comment]
Just an FYI, the general problem - backslashes preventing the automatic 'eating' of closing punctuation when typed manually - applies to all closing punctuation, not just single and double quotes.

In Clojure, for example, typing `(str h)` results in

    (str h)

Typing `(str \h)` results in

    (str \h))

**Comment by zmbc** [comment]
To generalize, this occurs whenever you've only typed one character after a backslash, and behaves the exact same way with `(` as with `"`.

Typing `(\zz)` or any other two character string after the backslash will not cause this error. It only occurs when the attempted closing `"` or `)` is one of the two characters immediately after a backslash.

**Comment by andyfriesen** [comment]
I have a fix for this at https://github.com/atom/bracket-matcher/pull/201 which I think solves for both terminating quotes and parentheses.

Until it gets merged, you can try it out by cloning the package into your ~/.atom/packages directory.

**Comment by zmbc** [comment]
Thanks! That fixes it. Hope it gets merged soon, this is a major annoyance that everyone shouldn't have to look around on Github in order to fix.

**Comment by mareklipka** [comment]
What's the status of this issue? I can confirm it still occurs in 1.13.0. Any progress on this?

**Comment by 50Wliu** [comment]
There is a PR, #201, that aims at fixing this, but there are some issues with that PR that need to be addressed before it can be merged.

**Comment by muppetjones** [comment]
@50Wliu If the only issue is the odd number of backslashes, I'd say merge it. I can't speak for everyone, but I use backslashes between parentheses and quotes pretty often. Multiple backslashes? On occasion. The package is completely unusable now, but that fix would at least make it better.

**Comment by WalterGR** [comment]
I agree.

If the PR improves the situation, then it should be accepted.

**Comment by 50Wliu** [comment]
I've created an updated PR at #276 that fixes the remaining issues I was seeing with #201.

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.16.0.

**Comment by imthansil** [comment]
How to fix this problem, i'm using atom 1.21.0... please help
