### ISSUE TITLE
nested brackets coloration

### ISSUE THREAD

**Issue by maxlevesque** [atom/bracket-matcher#84]
Hi, First of all thanks for the very good job. You're amazing :).  
I would really like to see nested brackets to have different colors. For instance, outter brackets in black, inner in red, etc.

**Comment by WalterGR** [comment]
Dupe of #170: "Rainbow"?

In any case, someone recently released a package that ostensibly does something similar: "My first package released (Coloured brackets)" - https://discuss.atom.io/t/my-first-package-released-coloured-brackets/21261.  I haven't tried it, but it might help.

**Comment by 50Wliu** [comment]
Thanks @WalterGR - this seems similar enough to #170, so let's keep the conversation unified over there.
