### ISSUE TITLE
Brackets Not Matching Properly In Markdown

### ISSUE THREAD

**Issue by bobrocke** [atom/bracket-matcher#85]
Brackets used in markdown don't highlight the matches properly if there is a soft wrap in between. See this screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/2962426/5232328/a6893f3c-771a-11e4-9eb0-b008e5f7ed22.jpeg)

The closing ] after themes is being matched with the space before the opening [.

See also the issue at: https://discuss.atom.io/t/brackets-not-matching-properly-in-markdown/13497

**Comment by kevinsawicki** [comment]
I believe this has been fixed by soft wrap fixes to how markers are rendered in core, this package just positions the cursors.

Please comment if you are still seeing this on Atom 1.0.5+.
