### ISSUE TITLE
Match {% %}

### ISSUE THREAD

**Issue by bobrocke** [atom/bracket-matcher#94]
Would it be possible match the `{%` `%}` pairs used by Twig for commands?

**Comment by EricKoziol** [comment]
Or support for custom pairs in general as _ and * for markdown would be useful. 
(This can be easily done by opening `bracket-matcher.js` and appending them to the `BracketMatcher.prototype.defaultPairs = {}` but any update to the plugin overwrites these custom matches.)

**Comment by screeny05** [comment]
+1

**Comment by musopr** [comment]
I would also like to see a custom bracket feature.The ability to match delimiters like `$` or `\{` in Latex math expressions would be excellent :)

**Comment by heisian** [comment]
definitely +1 on this - for e.g. when using Blade within Laravel to match {!! !!}

**Comment by 50Wliu** [comment]
Closing in favor of #121, which is more generic.
