### ISSUE TITLE
Atom 0.166.0

### ISSUE THREAD

**Issue by ineil** [atom/bracket-matcher#98]
This plugin has stopped highlighting content in Atom 0.166.0
(Using Bracket Matcher 0.64.0)

Have disabled, reenabled, rebooted - still no joy.

**Comment by kevinsawicki** [comment]
What theme are you using?

**Comment by williamboman** [comment]
+1

On same versions. I use `Seti` UI and `Seti Monokai` syntax.

**Comment by TreyTaylor** [comment]
+1

**Comment by lee-dohm** [comment]
The issue where brackets weren't being highlighted because of the change to the Shadow DOM was fixed in the latest release. Since there are other issues tracking the bugs in the themes, I'm going to close this one.

Let us know if this isn't fixed for you on the latest version.
